export default [
  {
    th: "06",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "A", jf: 10.26 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 12.32 },
          { character: "Marisa", type: "B", jf: 11.32 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.26 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.82 },
          { character: "Marisa", type: "B", jf: 10.58 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "A", jf: 10.15 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.82 },
          { character: "Marisa", type: "B", jf: 11.0 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.58 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.14 },
          { character: "Marisa", type: "B", jf: 10.26 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "07",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "A", jf: 10.17 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 11.0 },
          { character: "Marisa", type: "B", jf: 11.25 },
          { character: "Sakuya", type: "A", jf: 10.32 },
          { character: "Sakuya", type: "B", jf: 10.0 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.17 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.32 },
          { character: "Marisa", type: "B", jf: 10.81 },
          { character: "Sakuya", type: "A", jf: 10.32 },
          { character: "Sakuya", type: "B", jf: 10.0 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "A", jf: 12.1 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.21 },
          { character: "Marisa", type: "B", jf: 10.41 },
          { character: "Sakuya", type: "A", jf: 11.15 },
          { character: "Sakuya", type: "B", jf: 10.6 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.81 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Marisa", type: "A", jf: 10.81 },
          { character: "Marisa", type: "B", jf: 10.91 },
          { character: "Sakuya", type: "A", jf: 10.32 },
          { character: "Sakuya", type: "B", jf: 10.17 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "08",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 10.0 },
          { character: "Reimu & Yukari", route: "6B", jf: 10.0 },
          { character: "Marisa & Alice", route: "6A", jf: 10.0 },
          { character: "Marisa & Alice", route: "6B", jf: 9.36 },
          { character: "Sakuya & Remilia", route: "6A", jf: 10.0 },
          { character: "Sakuya & Remilia", route: "6B", jf: 9.36 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 10.0 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 10.0 },
          { character: "Reimu", route: "6A", jf: 12.52 },
          { character: "Reimu", route: "6B", jf: 12.52 },
          { character: "Yukari", route: "6A", jf: 11.7 },
          { character: "Yukari", route: "6B", jf: 11.7 },
          { character: "Marisa", route: "6A", jf: 12.76 },
          { character: "Marisa", route: "6B", jf: 12.76 },
          { character: "Alice", route: "6A", jf: 14.0 },
          { character: "Alice", route: "6B", jf: 14.0 },
          { character: "Sakuya", route: "6A", jf: 14.64 },
          { character: "Sakuya", route: "6B", jf: 14.64 },
          { character: "Remilia", route: "6A", jf: 12.0 },
          { character: "Remilia", route: "6B", jf: 12.0 },
          { character: "Youmu", route: "6A", jf: 10.0 },
          { character: "Youmu", route: "6B", jf: 10.0 },
          { character: "Yuyuko", route: "6A", jf: 12.52 },
          { character: "Yuyuko", route: "6B", jf: 12.52 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 10.0 },
          { character: "Reimu & Yukari", route: "6B", jf: 10.0 },
          { character: "Marisa & Alice", route: "6A", jf: 10.0 },
          { character: "Marisa & Alice", route: "6B", jf: 9.36 },
          { character: "Sakuya & Remilia", route: "6A", jf: 10.0 },
          { character: "Sakuya & Remilia", route: "6B", jf: 9.36 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 10.0 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 10.0 },
          { character: "Reimu", route: "6A", jf: 12.52 },
          { character: "Reimu", route: "6B", jf: 12.52 },
          { character: "Yukari", route: "6A", jf: 11.7 },
          { character: "Yukari", route: "6B", jf: 11.7 },
          { character: "Marisa", route: "6A", jf: 12.76 },
          { character: "Marisa", route: "6B", jf: 12.76 },
          { character: "Alice", route: "6A", jf: 14.0 },
          { character: "Alice", route: "6B", jf: 14.0 },
          { character: "Sakuya", route: "6A", jf: 14.64 },
          { character: "Sakuya", route: "6B", jf: 14.64 },
          { character: "Remilia", route: "6A", jf: 12.0 },
          { character: "Remilia", route: "6B", jf: 12.0 },
          { character: "Youmu", route: "6A", jf: 10.0 },
          { character: "Youmu", route: "6B", jf: 10.0 },
          { character: "Yuyuko", route: "6A", jf: 12.52 },
          { character: "Yuyuko", route: "6B", jf: 12.52 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 10.0 },
          { character: "Reimu & Yukari", route: "6B", jf: 10.0 },
          { character: "Marisa & Alice", route: "6A", jf: 10.0 },
          { character: "Marisa & Alice", route: "6B", jf: 10.0 },
          { character: "Sakuya & Remilia", route: "6A", jf: 10.14 },
          { character: "Sakuya & Remilia", route: "6B", jf: 10.14 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 10.14 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 10.14 },
          { character: "Reimu", route: "6A", jf: 13.9 },
          { character: "Reimu", route: "6B", jf: 13.9 },
          { character: "Yukari", route: "6A", jf: 11.0 },
          { character: "Yukari", route: "6B", jf: 11.0 },
          { character: "Marisa", route: "6A", jf: 12.35 },
          { character: "Marisa", route: "6B", jf: 12.35 },
          { character: "Alice", route: "6A", jf: 14.86 },
          { character: "Alice", route: "6B", jf: 14.86 },
          { character: "Sakuya", route: "6A", jf: 15.4 },
          { character: "Sakuya", route: "6B", jf: 15.4 },
          { character: "Remilia", route: "6A", jf: 12.14 },
          { character: "Remilia", route: "6B", jf: 12.14 },
          { character: "Youmu", route: "6A", jf: 10.14 },
          { character: "Youmu", route: "6B", jf: 10.14 },
          { character: "Yuyuko", route: "6A", jf: 13.0 },
          { character: "Yuyuko", route: "6B", jf: 13.0 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu & Yukari", jf: 10.0 },
          { character: "Marisa & Alice", jf: 10.0 },
          { character: "Sakuya & Remilia", jf: 10.26 },
          { character: "Youmu & Yuyuko", jf: 10.0 },
          { character: "Reimu", jf: 11.26 },
          { character: "Yukari", jf: 10.0 },
          { character: "Marisa", jf: 11.26 },
          { character: "Alice", jf: 12.0 },
          { character: "Sakuya", jf: 12.0 },
          { character: "Remilia", jf: 10.26 },
          { character: "Youmu", jf: 10.26 },
          { character: "Yuyuko", jf: 10.68 },
        ],
        remark: "",
      },
    },
    nn_all_spell: {
      Lunatic: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 11.58 },
          { character: "Reimu & Yukari", route: "6B", jf: 12.0 },
          { character: "Marisa & Alice", route: "6A", jf: 11.85 },
          { character: "Marisa & Alice", route: "6B", jf: 11.5 },
          { character: "Sakuya & Remilia", route: "6A", jf: 11.85 },
          { character: "Sakuya & Remilia", route: "6B", jf: 11.5 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 11.58 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 12.0 },
          { character: "Reimu", route: "6A", jf: 13.39 },
          { character: "Reimu", route: "6B", jf: 13.69 },
          { character: "Yukari", route: "6A", jf: 12.78 },
          { character: "Yukari", route: "6B", jf: 13.12 },
          { character: "Marisa", route: "6A", jf: 13.76 },
          { character: "Marisa", route: "6B", jf: 14.01 },
          { character: "Alice", route: "6A", jf: 15.0 },
          { character: "Alice", route: "6B", jf: 15.17 },
          { character: "Sakuya", route: "6A", jf: 15.32 },
          { character: "Sakuya", route: "6B", jf: 15.49 },
          { character: "Remilia", route: "6A", jf: 13.2 },
          { character: "Remilia", route: "6B", jf: 13.49 },
          { character: "Youmu", route: "6A", jf: 11.58 },
          { character: "Youmu", route: "6B", jf: 12.0 },
          { character: "Yuyuko", route: "6A", jf: 13.39 },
          { character: "Yuyuko", route: "6B", jf: 13.69 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 11.58 },
          { character: "Reimu & Yukari", route: "6B", jf: 12.0 },
          { character: "Marisa & Alice", route: "6A", jf: 11.85 },
          { character: "Marisa & Alice", route: "6B", jf: 11.5 },
          { character: "Sakuya & Remilia", route: "6A", jf: 11.85 },
          { character: "Sakuya & Remilia", route: "6B", jf: 11.5 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 11.58 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 12.0 },
          { character: "Reimu", route: "6A", jf: 13.39 },
          { character: "Reimu", route: "6B", jf: 13.69 },
          { character: "Yukari", route: "6A", jf: 12.78 },
          { character: "Yukari", route: "6B", jf: 13.12 },
          { character: "Marisa", route: "6A", jf: 13.76 },
          { character: "Marisa", route: "6B", jf: 14.01 },
          { character: "Alice", route: "6A", jf: 15.0 },
          { character: "Alice", route: "6B", jf: 15.17 },
          { character: "Sakuya", route: "6A", jf: 15.32 },
          { character: "Sakuya", route: "6B", jf: 15.49 },
          { character: "Remilia", route: "6A", jf: 13.2 },
          { character: "Remilia", route: "6B", jf: 13.49 },
          { character: "Youmu", route: "6A", jf: 11.58 },
          { character: "Youmu", route: "6B", jf: 12.0 },
          { character: "Yuyuko", route: "6A", jf: 13.39 },
          { character: "Yuyuko", route: "6B", jf: 13.69 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu & Yukari", route: "6A", jf: 11.58 },
          { character: "Reimu & Yukari", route: "6B", jf: 12.0 },
          { character: "Marisa & Alice", route: "6A", jf: 11.85 },
          { character: "Marisa & Alice", route: "6B", jf: 12.14 },
          { character: "Sakuya & Remilia", route: "6A", jf: 11.99 },
          { character: "Sakuya & Remilia", route: "6B", jf: 12.28 },
          { character: "Youmu & Yuyuko", route: "6A", jf: 11.72 },
          { character: "Youmu & Yuyuko", route: "6B", jf: 12.14 },
          { character: "Reimu", route: "6A", jf: 14.77 },
          { character: "Reimu", route: "6B", jf: 15.07 },
          { character: "Yukari", route: "6A", jf: 12.08 },
          { character: "Yukari", route: "6B", jf: 12.42 },
          { character: "Marisa", route: "6A", jf: 13.35 },
          { character: "Marisa", route: "6B", jf: 13.6 },
          { character: "Alice", route: "6A", jf: 15.86 },
          { character: "Alice", route: "6B", jf: 16.03 },
          { character: "Sakuya", route: "6A", jf: 16.08 },
          { character: "Sakuya", route: "6B", jf: 16.25 },
          { character: "Remilia", route: "6A", jf: 13.34 },
          { character: "Remilia", route: "6B", jf: 13.63 },
          { character: "Youmu", route: "6A", jf: 11.72 },
          { character: "Youmu", route: "6B", jf: 12.14 },
          { character: "Yuyuko", route: "6A", jf: 13.87 },
          { character: "Yuyuko", route: "6B", jf: 14.17 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu & Yukari", jf: 10.5 },
          { character: "Marisa & Alice", jf: 10.53 },
          { character: "Sakuya & Remilia", jf: 10.8 },
          { character: "Youmu & Yuyuko", jf: 10.53 },
          { character: "Reimu", jf: 11.76 },
          { character: "Yukari", jf: 10.5 },
          { character: "Marisa", jf: 11.8 },
          { character: "Alice", jf: 12.53 },
          { character: "Sakuya", jf: 12.53 },
          { character: "Remilia", jf: 10.8 },
          { character: "Youmu", jf: 10.8 },
          { character: "Yuyuko", jf: 11.21 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "10",
    nn: {
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.15 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Reimu", type: "C", jf: 10.29 },
          { character: "Marisa", type: "A", jf: 11.15 },
          { character: "Marisa", type: "B", jf: 8.83 },
          { character: "Marisa", type: "C", jf: 10.15 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Reimu", type: "C", jf: 10.21 },
          { character: "Marisa", type: "A", jf: 11.21 },
          { character: "Marisa", type: "B", jf: 8.92 },
          { character: "Marisa", type: "C", jf: 10.21 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.17 },
          { character: "Reimu", type: "B", jf: 10.0 },
          { character: "Reimu", type: "C", jf: 11.0 },
          { character: "Marisa", type: "A", jf: 11.32 },
          { character: "Marisa", type: "B", jf: 10.32 },
          { character: "Marisa", type: "C", jf: 10.17 },
        ],
        remark: "",
      },
    },
    nn_cross: {
      Lunatic: {
        data: [
          {
            character: "Reimu",
            type: "A",
            jf: [99.418, 99.253, 98.563, 96.678, 92.937, 87.084, 79.029, 67.964, 53.184], //jf数组的index代表miss数
          },
          {
            character: "Reimu",
            type: "B",
            jf: [99.401, 99.126, 98.099, 95.604, 91.12, 84.468, 75.345, 63.37, 49.78],
          },
          {
            character: "Reimu",
            type: "C",
            jf: [99.42, 99.265, 98.615, 96.835, 93.297, 87.754, 80.094, 69.49, 55.127],
          },
          {
            character: "Marisa",
            type: "A",
            jf: [99.433, 99.423, 99.394, 98.877, 96.925, 94.269, 88.474, 70.128, 55.66],
          },
          {
            character: "Marisa",
            type: "B",
            jf: [96.321, 83.056, 65.604, 57.009, 55.718, 0.0, 0.0, 0.0, 0.0],
          },
          {
            character: "Marisa",
            type: "C",
            jf: [99.364, 98.797, 96.762, 92.178, 84.639, 74.256, 61.34, 47.47, 35.983],
          },
        ],
        remark: "",
      },
    },
  },
  {
    th: "11",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.29 },
          { character: "Reimu", type: "C", jf: 10.15 },
          { character: "Marisa", type: "A", jf: 10.29 },
          { character: "Marisa", type: "B", jf: 10.29 },
          { character: "Marisa", type: "C", jf: 11.29 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.15 },
          { character: "Reimu", type: "C", jf: 10.15 },
          { character: "Marisa", type: "A", jf: 10.15 },
          { character: "Marisa", type: "B", jf: 10.29 },
          { character: "Marisa", type: "C", jf: 11.29 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.81 },
          { character: "Reimu", type: "C", jf: 11.0 },
          { character: "Marisa", type: "A", jf: 11.0 },
          { character: "Marisa", type: "B", jf: 11.17 },
          { character: "Marisa", type: "C", jf: 11.17 },
        ],
        remark: "",
      },
    },
    nn_cross: {
      Normal: {
        data: [
          {
            character: "Reimu",
            type: "A",
            jf: [19.171, 18.903, 18.153, 16.823, 15.159, 13.586, 12.396, 11.649, 11.251, 11.071, 11.003], //jf数组的index代表miss数
          },
          {
            character: "Reimu",
            type: "B",
            jf: [19.169, 18.919, 18.292, 17.271, 16.07, 14.976, 14.164, 13.658, 13.388, 13.264, 13.216],
          },
          {
            character: "Reimu",
            type: "C",
            jf: [19.173, 18.91, 18.202, 17.03, 15.689, 14.548, 13.785, 13.372, 13.189, 13.123, 13.104],
          },
          {
            character: "Marisa",
            type: "A",
            jf: [19.176, 18.908, 18.141, 16.813, 15.232, 13.834, 12.86, 12.305, 12.044, 11.943, 11.91],
          },
          {
            character: "Marisa",
            type: "B",
            jf: [19.195, 19.016, 18.414, 17.198, 15.532, 13.867, 12.573, 11.758, 11.332, 11.149, 11.084],
          },
          {
            character: "Marisa",
            type: "C",
            jf: [19.212, 19.152, 18.889, 18.175, 16.833, 14.991, 13.061, 11.443, 10.317, 9.648, 9.307],
          },
        ],
        remark: "",
      },
    },
  },
  {
    th: "12",
    nn: {
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.35 },
          { character: "Marisa", type: "A", jf: 11.15 },
          { character: "Marisa", type: "B", jf: 11.15 },
          { character: "Sanae", type: "A", jf: 11.0 },
          { character: "Sanae", type: "B", jf: 11.0 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.2 },
          { character: "Marisa", type: "A", jf: 10.88 },
          { character: "Marisa", type: "B", jf: 11.0 },
          { character: "Sanae", type: "A", jf: 11.0 },
          { character: "Sanae", type: "B", jf: 10.88 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 10.32 },
          { character: "Marisa", type: "A", jf: 10.17 },
          { character: "Marisa", type: "B", jf: 10.58 },
          { character: "Sanae", type: "A", jf: 10.58 },
          { character: "Sanae", type: "B", jf: 10.0 },
        ],
        remark: "",
      },
    },
    nn_cross: {
      Lunatic: {
        data: [
          {
            character: "Reimu",
            type: "A",
            jf: [99.416, 99.217, 98.304, 95.584, 89.748, 80.425], //jf数组的index代表miss数
          },
          {
            character: "Reimu",
            type: "B",
            jf: [99.429, 99.336, 98.839, 97.105, 92.722, 84.417],
          },
          {
            character: "Marisa",
            type: "A",
            jf: [99.431, 99.357, 98.954, 97.526, 93.852, 86.766],
          },
          {
            character: "Marisa",
            type: "B",
            jf: [99.433, 99.379, 99.063, 97.855, 94.508, 87.542],
          },
          {
            character: "Sanae",
            type: "A",
            jf: [99.432, 99.366, 98.994, 97.614, 93.904, 86.404],
          },
          {
            character: "Sanae",
            type: "B",
            jf: [99.429, 99.333, 98.827, 97.094, 92.811, 84.951],
          },
        ],
        remark: "",
      },
    },
  },
  {
    th: "13",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.0 },
          { character: "Sanae", jf: 11.47 },
          { character: "Youmu", jf: 10.0 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.0 },
          { character: "Sanae", jf: 11.47 },
          { character: "Youmu", jf: 10.0 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.0 },
          { character: "Sanae", jf: 11.55 },
          { character: "Youmu", jf: 10.0 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 10.17 },
          { character: "Sanae", jf: 11.0 },
          { character: "Youmu", jf: 10.17 },
        ],
        remark: "",
      },
    },
    nn_all_spell: {
      Lunatic: {
        data: [
          { character: "Reimu", jf: 10.29 },
          { character: "Marisa", jf: 11.22 },
          { character: "Sanae", jf: 12.23 },
          { character: "Youmu", jf: 10.29 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", jf: 10.29 },
          { character: "Marisa", jf: 11.22 },
          { character: "Sanae", jf: 12.23 },
          { character: "Youmu", jf: 10.29 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", jf: 10.29 },
          { character: "Marisa", jf: 11.22 },
          { character: "Sanae", jf: 12.21 },
          { character: "Youmu", jf: 10.29 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "14",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 14.62 },
          { character: "Marisa", type: "A", jf: 15.64 },
          { character: "Marisa", type: "B", jf: 13.62 },
          { character: "Sakuya", type: "A", jf: 10.0 },
          { character: "Sakuya", type: "B", jf: 15.64 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 14.03 },
          { character: "Marisa", type: "A", jf: 15.06 },
          { character: "Marisa", type: "B", jf: 13.0 },
          { character: "Sakuya", type: "A", jf: 10.0 },
          { character: "Sakuya", type: "B", jf: 15.64 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "A", jf: 9.83 },
          { character: "Reimu", type: "B", jf: 14.0 },
          { character: "Marisa", type: "A", jf: 15.0 },
          { character: "Marisa", type: "B", jf: 13.0 },
          { character: "Sakuya", type: "A", jf: 10.0 },
          { character: "Sakuya", type: "B", jf: 15.31 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "A", jf: 10.0 },
          { character: "Reimu", type: "B", jf: 11.0 },
          { character: "Marisa", type: "A", jf: 12.0 },
          { character: "Marisa", type: "B", jf: 11.0 },
          { character: "Sakuya", type: "A", jf: 10.0 },
          { character: "Sakuya", type: "B", jf: 12.0 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "15",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.42 },
          { character: "Sanae", jf: 11.0 },
          { character: "Reisen", jf: 11.0 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.42 },
          { character: "Sanae", jf: 11.0 },
          { character: "Reisen", jf: 11.0 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.54 },
          { character: "Sanae", jf: 11.27 },
          { character: "Reisen", jf: 11.27 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Marisa", jf: 11.42 },
          { character: "Sanae", jf: 11.42 },
          { character: "Reisen", jf: 11.42 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "16",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "Spring", jf: 11.68 },
          { character: "Cirno", type: "Spring", jf: 11.81 },
          { character: "Aya", type: "Spring", jf: 12.0 },
          { character: "Marisa", type: "Spring", jf: 11.58 },
          { character: "Reimu", type: "Summer", jf: 11.68 },
          { character: "Cirno", type: "Summer", jf: 11.81 },
          { character: "Aya", type: "Summer", jf: 12.0 },
          { character: "Marisa", type: "Summer", jf: 11.58 },
          { character: "Reimu", type: "Autumn", jf: 10.0 },
          { character: "Cirno", type: "Autumn", jf: 10.38 },
          { character: "Aya", type: "Autumn", jf: 10.68 },
          { character: "Marisa", type: "Autumn", jf: 10.0 },
          { character: "Reimu", type: "Winter", jf: 10.0 },
          { character: "Cirno", type: "Winter", jf: 10.38 },
          { character: "Aya", type: "Winter", jf: 10.68 },
          { character: "Marisa", type: "Winter", jf: 10.14 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "Spring", jf: 11.68 },
          { character: "Cirno", type: "Spring", jf: 11.81 },
          { character: "Aya", type: "Spring", jf: 12.0 },
          { character: "Marisa", type: "Spring", jf: 11.58 },
          { character: "Reimu", type: "Summer", jf: 11.68 },
          { character: "Cirno", type: "Summer", jf: 11.81 },
          { character: "Aya", type: "Summer", jf: 12.0 },
          { character: "Marisa", type: "Summer", jf: 11.58 },
          { character: "Reimu", type: "Autumn", jf: 10.0 },
          { character: "Cirno", type: "Autumn", jf: 10.38 },
          { character: "Aya", type: "Autumn", jf: 10.68 },
          { character: "Marisa", type: "Autumn", jf: 10.0 },
          { character: "Reimu", type: "Winter", jf: 10.0 },
          { character: "Cirno", type: "Winter", jf: 10.38 },
          { character: "Aya", type: "Winter", jf: 10.68 },
          { character: "Marisa", type: "Winter", jf: 10.14 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "Spring", jf: 11.72 },
          { character: "Cirno", type: "Spring", jf: 12.08 },
          { character: "Aya", type: "Spring", jf: 12.22 },
          { character: "Marisa", type: "Spring", jf: 11.84 },
          { character: "Reimu", type: "Summer", jf: 11.65 },
          { character: "Cirno", type: "Summer", jf: 12.01 },
          { character: "Aya", type: "Summer", jf: 12.15 },
          { character: "Marisa", type: "Summer", jf: 11.77 },
          { character: "Reimu", type: "Autumn", jf: 10.06 },
          { character: "Cirno", type: "Autumn", jf: 10.67 },
          { character: "Aya", type: "Autumn", jf: 10.91 },
          { character: "Marisa", type: "Autumn", jf: 10.27 },
          { character: "Reimu", type: "Winter", jf: 10.0 },
          { character: "Cirno", type: "Winter", jf: 10.61 },
          { character: "Aya", type: "Winter", jf: 10.85 },
          { character: "Marisa", type: "Winter", jf: 10.35 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", jf: 10.0 },
          { character: "Cirno", jf: 12.0 },
          { character: "Aya", jf: 12.0 },
          { character: "Marisa", jf: 11.74 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "17",
    nn: {
      Lunatic: {
        data: [
          { character: "Reimu", type: "Wolf", jf: 10.5 },
          { character: "Reimu", type: "Otter", jf: 11.5 },
          { character: "Reimu", type: "Eagle", jf: 11.3 },
          { character: "Marisa", type: "Wolf", jf: 10.2 },
          { character: "Marisa", type: "Otter", jf: 11.0 },
          { character: "Marisa", type: "Eagle", jf: 10.7 },
          { character: "Youmu", type: "Wolf", jf: 10.0 },
          { character: "Youmu", type: "Otter", jf: 10.2 },
          { character: "Youmu", type: "Eagle", jf: 12.5 },
        ],
        remark: "",
      },
      Hard: {
        data: [
          { character: "Reimu", type: "Wolf", jf: 10.5 },
          { character: "Reimu", type: "Otter", jf: 11.5 },
          { character: "Reimu", type: "Eagle", jf: 11.3 },
          { character: "Marisa", type: "Wolf", jf: 10.2 },
          { character: "Marisa", type: "Otter", jf: 11.0 },
          { character: "Marisa", type: "Eagle", jf: 10.7 },
          { character: "Youmu", type: "Wolf", jf: 10.0 },
          { character: "Youmu", type: "Otter", jf: 10.2 },
          { character: "Youmu", type: "Eagle", jf: 12.5 },
        ],
        remark: "",
      },
      Normal: {
        data: [
          { character: "Reimu", type: "Wolf", jf: 10.24 },
          { character: "Reimu", type: "Otter", jf: 11.48 },
          { character: "Reimu", type: "Eagle", jf: 11.08 },
          { character: "Marisa", type: "Wolf", jf: 10.0 },
          { character: "Marisa", type: "Otter", jf: 11.18 },
          { character: "Marisa", type: "Eagle", jf: 10.48 },
          { character: "Youmu", type: "Wolf", jf: 10.0 },
          { character: "Youmu", type: "Otter", jf: 10.0 },
          { character: "Youmu", type: "Eagle", jf: 12.24 },
        ],
        remark: "",
      },
      Extra: {
        data: [
          { character: "Reimu", type: "Wolf", jf: 10.17 },
          { character: "Reimu", type: "Otter", jf: 11.17 },
          { character: "Reimu", type: "Eagle", jf: 10.81 },
          { character: "Marisa", type: "Wolf", jf: 10.0 },
          { character: "Marisa", type: "Otter", jf: 10.81 },
          { character: "Marisa", type: "Eagle", jf: 10.32 },
          { character: "Youmu", type: "Wolf", jf: 10.0 },
          { character: "Youmu", type: "Otter", jf: 10.0 },
          { character: "Youmu", type: "Eagle", jf: 11.09 },
        ],
        remark: "",
      },
    },
  },
  {
    th: "18",
    nn: {
      Default: {
        remark: `机体基础分（每miss一次减一分）
        灵梦10.13 魔理沙12 早苗10.17 咲夜10
        初始卡牌分数修正（注意：初始只允许携带本表中的卡牌，是否携带“可靠的弟子狸”依赛前商议而定）
        规则：初始统一只带“可靠的弟子狸”，买卡只买残雷钱火力
        迷你八卦炉 迷你八卦炉（导弹） -1.5
        爆裂赤蛙 阴阳玉（针） 上海人偶 放入蛇蜕的护身符 -1.4
        阴阳玉 -1.3
        女仆飞刀 半灵的一半 -1.2
        平安归来蛙护身符 女仆飞刀（跳弹） Ice Fairy（冰之妖精） -0.2
        虹龙洞避弹分数表，作者：YukariM 特别鸣谢：樱小路Asahi、園田琴梨、旅鼠 以及其他为本表做出贡献的测试者和玩家们`,
      },
      Extra: {
        remark: `机体基础分（每miss一次减一分）
        灵梦10 魔理沙10.7 早苗10.3 咲夜10.3
        规则：初始统一只带“可靠的弟子狸”，买卡只买残雷钱火力
        虹龙洞避弹分数表，作者：YukariM 特别鸣谢：樱小路Asahi、園田琴梨、旅鼠 以及其他为本表做出贡献的测试者和玩家们`,
      },
    },
  },
];